$CC = cc

compile:
	cc -c *.c
	cc -o cat 	cat.o
	cc -o dirname 	dirname.o
	cc -o echo 	echo.o
	cc -o ln	ln.o
	cc -o mkdir	mkdir.o
	cc -o pwd	pwd.o
	cc -o rmdir	rmdir.o
	cc -o touch	touch.o
	cc -o yes	yes.o
clean:
	rm *.o cat dirname echo ln mkdir pwd rmdir touch yes
